# Generated by Django 5.0.2 on 2025-11-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_bankaccount_otpcode_wallet_wallettransaction_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OtpCode",
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="txn_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdraw", "Withdraw"),
                    ("order_debit", "Order Debit"),
                    ("owner_credit", "Owner Credit"),
                    ("delivery_fee", "Delivery Fee"),
                    ("delivery_earning", "Delivery Earning"),
                ],
                max_length=20,
            ),
        ),
    ]
